import { siteConfig, orgId, localBusinessId } from '../site-config'

const offerCatalog = [
  {
    slug: 'seo',
    name: 'SEO 搜尋引擎優化',
    description: '提升網站在 Google 搜尋結果中的排名，增加自然流量與品牌曝光',
    serviceType: '搜尋引擎優化',
    minPrice: '15000',
    price: '15000',
    unitText: '月',
  },
  {
    slug: 'geo',
    name: 'GEO 生成式引擎優化',
    description: '讓 ChatGPT、Gemini、Claude 等 AI 優先引用您的品牌，搶占 AI 搜尋時代先機',
    serviceType: '生成式引擎優化',
    minPrice: '25000',
    price: '25000',
    unitText: '月',
  },
  {
    slug: 'aeo',
    name: 'AEO 答案引擎優化',
    description: '成為 Perplexity、Google AI Overview 的首選答案來源，提升品牌權威性',
    serviceType: '答案引擎優化',
    minPrice: '20000',
    price: '20000',
    unitText: '月',
  },
  {
    slug: 'web-development',
    name: '網站建置與軟體開發',
    description: '客製化企業官網、電商平台、APP、CMS/ERP 系統開發',
    serviceType: '網站開發',
    minPrice: '25000',
    price: '40000',
    unitText: '專案',
  },
  {
    slug: 'digital-ads',
    name: '數位廣告投放',
    description: 'Google Ads、Meta 廣告、LINE LAP 精準投放，最大化廣告效益',
    serviceType: '數位廣告',
    minPrice: '7500',
    price: '10000',
    unitText: '月',
  },
  {
    slug: 'social-media',
    name: '社群經營',
    description: 'Instagram、Facebook、LINE 官方帳號經營，建立品牌社群影響力',
    serviceType: '社群行銷',
    minPrice: '7500',
    price: '12500',
    unitText: '月',
  },
  {
    slug: 'video',
    name: '短影音與形象影片製作',
    description: 'TikTok、Reels 短影音、企業形象影片、產品宣傳影片製作',
    serviceType: '影片製作',
    minPrice: '7500',
    price: '15000',
    unitText: '支',
  },
  {
    slug: 'ai-tools',
    name: 'AI 工具開發',
    description: '客製化 AI 聊天機器人、智能客服系統、AI 自動化工具開發',
    serviceType: 'AI 開發',
    minPrice: '25000',
    price: '50000',
    unitText: '專案',
  },
] as const

export const localBusinessSchema = {
  '@context': 'https://schema.org',
  '@type': ['LocalBusiness', 'ProfessionalService', 'MarketingAgency'],
  '@id': localBusinessId,
  name: siteConfig.name,
  alternateName: siteConfig.alternateNames as unknown as string[],
  description: siteConfig.description,
  url: siteConfig.url,
  logo: {
    '@type': 'ImageObject',
    url: `${siteConfig.url}/logo.png`,
    width: 512,
    height: 512,
  },
  image: [`${siteConfig.url}/logo.png`],
  telephone: siteConfig.telephone,
  email: siteConfig.email,
  priceRange: siteConfig.priceRange,
  currenciesAccepted: 'TWD',
  paymentAccepted: '銀行轉帳, 信用卡, 現金',
  foundingDate: siteConfig.foundingDate,
  founder: { '@type': 'Person', name: '隼訊團隊' },
  address: {
    '@type': 'PostalAddress',
    streetAddress: siteConfig.address.streetAddress,
    addressLocality: siteConfig.address.addressLocality,
    addressRegion: siteConfig.address.addressRegion,
    postalCode: siteConfig.address.postalCode,
    addressCountry: siteConfig.address.addressCountry,
  },
  geo: {
    '@type': 'GeoCoordinates',
    latitude: siteConfig.geo.latitude,
    longitude: siteConfig.geo.longitude,
  },
  openingHoursSpecification: [
    {
      '@type': 'OpeningHoursSpecification',
      dayOfWeek: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
      opens: '09:00',
      closes: '18:00',
    },
  ],
  areaServed: [
    { '@type': 'Country', name: '台灣', '@id': 'https://www.wikidata.org/wiki/Q865' },
    ...siteConfig.areasServed.map((a) => ({
      '@type': 'AdministrativeArea',
      name: a.name,
      containedInPlace: { '@type': 'Country', name: '台灣' },
    })),
  ],
  sameAs: siteConfig.socialLinks as unknown as string[],
  slogan: siteConfig.slogan,
  knowsAbout: ['SEO', 'GEO', 'AEO', '數位行銷', '網站開發', 'AI 工具', '社群經營'],
  knowsLanguage: ['zh-TW', 'en'],
  hasOfferCatalog: {
    '@type': 'OfferCatalog',
    name: '數位行銷服務',
    itemListElement: offerCatalog.map((item) => ({
      '@type': 'Offer',
      itemOffered: {
        '@type': 'Service',
        '@id': `${siteConfig.url}/#service-${item.slug}`,
        name: item.name,
        description: item.description,
        provider: { '@id': orgId },
        areaServed: { '@type': 'Country', name: '台灣' },
        serviceType: item.serviceType,
        url: `${siteConfig.url}/services/${item.slug}`,
      },
      priceSpecification: {
        '@type': 'PriceSpecification',
        priceCurrency: 'TWD',
        price: item.price,
        minPrice: item.minPrice,
        unitText: item.unitText,
      },
    })),
  },
}

export { offerCatalog }
