import type { Locale } from './config'
const errors = {
  'zh-tw': ['請填寫姓名、Email 與訊息內容。', '服務類別格式不正確，請重新選擇後再送出。', '不支援此語言。', '郵件服務未正確設定，請改用 Email 或電話聯繫。', '郵件發送失敗。請重試或改用 Email 聯繫。', '訊息已成功送出！', '未收到有效的送出確認，請重試或改用 Email 聯繫。', '伺服器回應為空白。', '發送失敗，請稍後再試。', '請輸入有效的 Email 地址。'],
  en: ['Please enter your name, email and message.', 'Invalid service selection. Please select again.', 'This language is not supported.', 'Email delivery is not configured. Please contact us by email or phone.', 'Email delivery failed. Please retry or contact us by email.', 'Your message was sent successfully!', 'No valid submission confirmation was received. Please retry or contact us by email.', 'The server returned an empty response.', 'Submission failed. Please try again later.', 'Please enter a valid email address.'],
  ja: ['お名前、メールアドレス、メッセージを入力してください。', 'サービスの選択が無効です。選び直してください。', 'この言語には対応していません。', 'メール送信の設定が完了していません。メールまたは電話でお問い合わせください。', 'メール送信に失敗しました。再試行するか、メールでお問い合わせください。', 'メッセージを送信しました。', '有効な送信確認を受信できませんでした。再試行するか、メールでお問い合わせください。', 'サーバーからの応答が空でした。', '送信に失敗しました。時間をおいて再度お試しください。', '有効なメールアドレスを入力してください。'],
  ko: ['이름, 이메일과 문의 내용을 입력해 주세요.', '서비스 선택이 올바르지 않습니다. 다시 선택해 주세요.', '지원하지 않는 언어입니다.', '메일 전송 설정이 완료되지 않았습니다. 이메일이나 전화로 문의해 주세요.', '메일 전송에 실패했습니다. 다시 시도하거나 이메일로 문의해 주세요.', '문의가 전송되었습니다!', '유효한 전송 확인을 받지 못했습니다. 다시 시도하거나 이메일로 문의해 주세요.', '서버 응답이 비어 있습니다.', '전송에 실패했습니다. 잠시 후 다시 시도해 주세요.', '올바른 이메일 주소를 입력해 주세요.'],
  'zh-hans': ['请填写姓名、Email 与消息内容。', '服务类别格式不正确，请重新选择后提交。', '不支持此语言。', '邮件服务未正确配置，请通过 Email 或电话联系。', '邮件发送失败。请重试或通过 Email 联系。', '消息已成功发送！', '未收到有效的提交确认，请重试或通过 Email 联系。', '服务器响应为空。', '发送失败，请稍后重试。', '请输入有效的 Email 地址。'],
  es: ['Indica tu nombre, correo y mensaje.', 'Selección de servicio no válida. Vuelve a elegir.', 'Este idioma no está disponible.', 'El envío de correo no está configurado. Contáctanos por correo o teléfono.', 'No se pudo enviar el correo. Inténtalo de nuevo o contáctanos por correo.', '¡Tu mensaje se ha enviado!', 'No se recibió una confirmación válida. Inténtalo de nuevo o contáctanos por correo.', 'El servidor devolvió una respuesta vacía.', 'El envío falló. Inténtalo de nuevo más tarde.', 'Introduce una dirección de correo válida.'],
  fr: ['Veuillez saisir votre nom, votre e-mail et votre message.', 'Service sélectionné non valide. Veuillez réessayer.', 'Cette langue n’est pas prise en charge.', 'L’envoi des e-mails n’est pas configuré. Contactez-nous par e-mail ou téléphone.', 'Échec de l’envoi. Réessayez ou contactez-nous par e-mail.', 'Votre message a été envoyé !', 'Aucune confirmation valide n’a été reçue. Réessayez ou contactez-nous par e-mail.', 'Le serveur a renvoyé une réponse vide.', 'Échec de l’envoi. Veuillez réessayer plus tard.', 'Veuillez saisir une adresse e-mail valide.'],
  de: ['Bitte geben Sie Ihren Namen, Ihre E-Mail-Adresse und Ihre Nachricht ein.', 'Ungültige Dienstauswahl. Bitte wählen Sie erneut.', 'Diese Sprache wird nicht unterstützt.', 'Der E-Mail-Versand ist nicht eingerichtet. Bitte kontaktieren Sie uns per E-Mail oder Telefon.', 'Der E-Mail-Versand ist fehlgeschlagen. Bitte versuchen Sie es erneut oder schreiben Sie uns eine E-Mail.', 'Ihre Nachricht wurde gesendet!', 'Es wurde keine gültige Sendebestätigung empfangen. Bitte versuchen Sie es erneut oder schreiben Sie uns eine E-Mail.', 'Die Serverantwort war leer.', 'Senden fehlgeschlagen. Bitte versuchen Sie es später erneut.', 'Bitte geben Sie eine gültige E-Mail-Adresse ein.'],
  pt: ['Informe seu nome, e-mail e mensagem.', 'Seleção de serviço inválida. Selecione novamente.', 'Este idioma não é compatível.', 'O envio de e-mail não está configurado. Entre em contato por e-mail ou telefone.', 'Falha no envio do e-mail. Tente novamente ou entre em contato por e-mail.', 'Sua mensagem foi enviada!', 'Não recebemos uma confirmação válida. Tente novamente ou entre em contato por e-mail.', 'O servidor retornou uma resposta vazia.', 'Falha no envio. Tente novamente mais tarde.', 'Informe um endereço de e-mail válido.'],
} satisfies Record<Locale, string[]>
export function contactMessages(locale: Locale) {
  const [required, service, invalidLocale, configuration, failed, sent, confirmation, empty, retry, email] = errors[locale]
  return { required, service, invalidLocale, configuration, failed, sent, confirmation, empty, retry, email }
}
