import type { Locale } from './config'
const rows = {
  'zh-tw': ['語言', '建議使用的語言', '切換語言', '關閉語言建議', '切換語言將離開此頁，尚未送出的表單內容會遺失。確定切換？', '接受九種語言的文字詢價，我們可透過翻譯協助溝通；電話服務語言請先以 Email 確認。', '找不到這個頁面', '網址可能已變更，請回首頁尋找服務與案例。', '回首頁', "隱私權政策", "服務條款", "我們將使用您提供的資料回覆詢問及聯絡合作。送出前請閱讀隱私權政策；公司名稱與服務分類為選填。"],
  en: ['Language', 'Suggested language', 'Switch language', 'Dismiss language suggestion', 'Switching languages will leave this page and discard your unsent form. Continue?', 'We accept written inquiries in nine languages and can use translation to assist communication. Please confirm telephone service languages by email.', 'Page not found', 'The address may have changed. Return home to explore our services and projects.', 'Back to home', "Privacy Policy (Traditional Chinese)", "Terms of Service (Traditional Chinese)", "We use your details to respond to your inquiry and discuss cooperation. Read our privacy policy before submitting; company and service fields are optional."],
  ja: ['言語', 'おすすめの言語', '言語を切り替える', '言語の提案を閉じる', '言語を切り替えるとこのページを離れ、未送信の入力内容が失われます。続けますか？', '9言語でのお問い合わせを文章で受け付け、翻訳を用いて対応できます。電話対応の言語は事前にメールでご確認ください。', 'ページが見つかりません', 'URL が変更された可能性があります。ホームからサービスや事例をご覧ください。', 'ホームに戻る', "プライバシーポリシー（繁体字中国語）", "利用規約（繁体字中国語）", "ご提供いただく情報は、お問い合わせへの回答と商談の連絡に使用します。送信前にプライバシーポリシーをご確認ください。会社名とサービスの選択は任意です。"],
  ko: ['언어', '추천 언어', '언어 변경', '언어 제안 닫기', '언어를 변경하면 이 페이지를 떠나며 제출하지 않은 내용이 사라집니다. 계속하시겠습니까?', '9개 언어로 작성된 문의를 받으며 번역을 활용해 소통할 수 있습니다. 전화 상담 가능 언어는 이메일로 먼저 확인해 주세요.', '페이지를 찾을 수 없습니다', '주소가 변경되었을 수 있습니다. 홈에서 서비스와 프로젝트를 확인해 주세요.', '홈으로 돌아가기', "개인정보 처리방침 (중국어 번체)", "이용약관 (중국어 번체)", "제공하신 정보는 문의 답변과 협업 연락에 사용합니다. 제출 전에 개인정보 처리방침을 읽어 주세요. 회사명과 서비스 선택은 선택 사항입니다."],
  'zh-hans': ['语言', '建议使用的语言', '切换语言', '关闭语言建议', '切换语言将离开此页，尚未提交的表单内容会丢失。确定切换？', '接受九种语言的文字咨询，我们可通过翻译协助沟通；电话服务语言请先通过 Email 确认。', '找不到这个页面', '网址可能已变更，请回首页查找服务与案例。', '返回首页', "隐私权政策（繁体中文）", "服务条款（繁体中文）", "我们将使用您提供的资料回复咨询及联系合作。提交前请阅读隐私权政策；公司名称与服务分类为选填。"],
  es: ['Idioma', 'Idioma sugerido', 'Cambiar idioma', 'Cerrar sugerencia de idioma', 'Cambiar de idioma cerrará esta página y descartará el formulario sin enviar. ¿Continuar?', 'Aceptamos consultas escritas en nueve idiomas y podemos ayudarnos de la traducción para comunicarnos. Confirma por correo los idiomas disponibles para llamadas.', 'Página no encontrada', 'La dirección puede haber cambiado. Vuelve al inicio para ver nuestros servicios y proyectos.', 'Volver al inicio', "Política de privacidad (chino tradicional)", "Términos del servicio (chino tradicional)", "Usamos tus datos para responder a tu consulta y hablar sobre la colaboración. Lee la política de privacidad antes de enviar; la empresa y el servicio son opcionales."],
  fr: ['Langue', 'Langue suggérée', 'Changer de langue', 'Fermer la suggestion de langue', 'Changer de langue quittera cette page et effacera le formulaire non envoyé. Continuer ?', 'Nous acceptons les demandes écrites en neuf langues et pouvons utiliser la traduction pour communiquer. Veuillez confirmer par e-mail les langues disponibles par téléphone.', 'Page introuvable', 'L’adresse a peut-être changé. Retrouvez nos services et projets sur la page d’accueil.', 'Retour à l’accueil', "Politique de confidentialité (chinois traditionnel)", "Conditions de service (chinois traditionnel)", "Nous utilisons vos informations pour répondre à votre demande et discuter d’une collaboration. Consultez la politique de confidentialité avant l’envoi ; les champs entreprise et service sont facultatifs."],
  de: ['Sprache', 'Vorgeschlagene Sprache', 'Sprache wechseln', 'Sprachvorschlag schließen', 'Beim Sprachwechsel verlassen Sie diese Seite. Nicht gesendete Formulareingaben gehen verloren. Fortfahren?', 'Wir nehmen schriftliche Anfragen in neun Sprachen entgegen und können Übersetzungen zur Verständigung nutzen. Bitte klären Sie die verfügbaren Telefonsprachen vorab per E-Mail.', 'Seite nicht gefunden', 'Die Adresse hat sich möglicherweise geändert. Auf der Startseite finden Sie unsere Leistungen und Projekte.', 'Zur Startseite', "Datenschutzerklärung (Traditionelles Chinesisch)", "Nutzungsbedingungen (Traditionelles Chinesisch)", "Wir verwenden Ihre Angaben zur Beantwortung Ihrer Anfrage und zur Besprechung einer Zusammenarbeit. Lesen Sie vor dem Absenden die Datenschutzerklärung; Firma und Leistung sind freiwillige Angaben."],
  pt: ['Idioma', 'Idioma sugerido', 'Alterar idioma', 'Fechar sugestão de idioma', 'Alterar o idioma sairá desta página e descartará o formulário não enviado. Continuar?', 'Aceitamos consultas por escrito em nove idiomas e podemos usar tradução para facilitar a comunicação. Confirme por e-mail os idiomas disponíveis para atendimento telefônico.', 'Página não encontrada', 'O endereço pode ter mudado. Volte ao início para conhecer nossos serviços e projetos.', 'Voltar ao início', "Política de privacidade (chinês tradicional)", "Termos de serviço (chinês tradicional)", "Usamos seus dados para responder à consulta e conversar sobre a colaboração. Leia a política de privacidade antes de enviar; empresa e serviço são opcionais."],
} satisfies Record<Locale, string[]>
export function languageUi(locale: Locale) {
  const [label, suggestion, change, dismiss, unsent, inquiry, notFound, notFoundDescription, home, privacy, terms, privacyNotice] = rows[locale]
  return { label, suggestion, change, dismiss, unsent, inquiry, notFound, notFoundDescription, home, privacy, terms, privacyNotice }
}
